"https://{default}/":
    type: upstream
    upstream: "demo:php"

"http://{default}/":
    type: redirect
    to: "https://{default}/"

"https://static.{default}/":
    type: upstream
    upstream: "demo:php"
    cache:
        enabled: true
        # Base the cache on the session cookie. Ignore all other cookies.
        cookies: ['/^SS?ESS/']
