mysql:
    type: mariadb:10.5
    disk: 2048
    configuration:
        schemas:
            - main
            - legacy
        endpoints:
            admin:
                default_schema: main
                privileges:
                    main: admin
                    legacy: admin
            viewer:
                privileges:
                    main: ro
rediscache:
    type: redis:5.0
#elasticsearch:
#    type: elasticsearch:6.5
#    disk: 256
